const lessons = [
  { "id": 1, "title": "What is RSpec?", "description": "Understand the purpose of RSpec and how it differs from other testing frameworks." },
  { "id": 2, "title": "Installing RSpec", "description": "Set up RSpec in a Ruby project using Bundler." },
  { "id": 3, "title": "Running Your First Spec", "description": "Execute your first RSpec test and understand the output." },
  { "id": 4, "title": "describe Blocks", "description": "Group related tests using describe blocks." },
  { "id": 5, "title": "it Blocks", "description": "Define individual examples with it blocks." },
  { "id": 6, "title": "Basic Expectations", "description": "Write expectations using expect().to." },
  { "id": 7, "title": "Equality Matchers", "description": "Use eq, eql, and equal matchers correctly." },
  { "id": 8, "title": "Truthiness Matchers", "description": "Test true, false, and nil values." },
  { "id": 9, "title": "Comparison Matchers", "description": "Use be >, be <, and other comparison matchers." },
  { "id": 10, "title": "Collection Matchers", "description": "Test arrays and hashes using include and match_array." },

  { "id": 11, "title": "String Matchers", "description": "Test strings with start_with, end_with, and match." },
  { "id": 12, "title": "Type Matchers", "description": "Use be_a and kind_of matchers." },
  { "id": 13, "title": "Predicate Matchers", "description": "Use be_empty, be_valid and custom predicates." },
  { "id": 14, "title": "Using subject", "description": "Define and use subject in your specs." },
  { "id": 15, "title": "Using let", "description": "Create memoized helper variables with let." },
  { "id": 16, "title": "let vs let!", "description": "Understand lazy vs eager evaluation." },
  { "id": 17, "title": "Nested describe Blocks", "description": "Organize specs with nested contexts." },
  { "id": 18, "title": "context Blocks", "description": "Use context to describe different states." },
  { "id": 19, "title": "before Hooks", "description": "Run setup code with before." },
  { "id": 20, "title": "after Hooks", "description": "Run teardown code with after." },

  { "id": 21, "title": "around Hooks", "description": "Wrap examples with around hooks." },
  { "id": 22, "title": "Multiple Expectations", "description": "Write more than one expectation per example." },
  { "id": 23, "title": "aggregate_failures", "description": "Group failures in a single example." },
  { "id": 24, "title": "Pending Examples", "description": "Mark tests as pending or skipped." },
  { "id": 25, "title": "Focused Specs", "description": "Run specific examples using fit and fdescribe." },
  { "id": 26, "title": "Shared Contexts", "description": "Reuse setup code across specs." },
  { "id": 27, "title": "Shared Examples", "description": "Reuse behavior definitions." },
  { "id": 28, "title": "Custom Matchers (Basic)", "description": "Create your first custom matcher." },
  { "id": 29, "title": "Failure Messages", "description": "Customize matcher failure output." },
  { "id": 30, "title": "Composing Matchers", "description": "Combine matchers using and/or." },

  { "id": 31, "title": "Spies Basics", "description": "Observe method calls without stubbing." },
  { "id": 32, "title": "allow and receive", "description": "Stub methods using allow().to receive." },
  { "id": 33, "title": "expect to receive", "description": "Set expectations on method calls." },
  { "id": 34, "title": "Return Values in Mocks", "description": "Configure mocked return values." },
  { "id": 35, "title": "Raising Errors", "description": "Test exceptions using raise_error." },
  { "id": 36, "title": "Yielding Blocks", "description": "Test methods that yield blocks." },
  { "id": 37, "title": "Instance Doubles", "description": "Use instance_double safely." },
  { "id": 38, "title": "Class Doubles", "description": "Use class_double for constants." },
  { "id": 39, "title": "Verifying Doubles", "description": "Ensure mocks match real objects." },
  { "id": 40, "title": "Partial Doubles", "description": "Stub real objects carefully." },

  { "id": 41, "title": "Stubbing Constants", "description": "Override constants during tests." },
  { "id": 42, "title": "Message Chains", "description": "Stub chained method calls." },
  { "id": 43, "title": "have_received Matcher", "description": "Verify spies after execution." },
  { "id": 44, "title": "Order of Calls", "description": "Test method call order." },
  { "id": 45, "title": "Argument Matching", "description": "Match method arguments." },
  { "id": 46, "title": "Time Helpers", "description": "Freeze and travel time in tests." },
  { "id": 47, "title": "Testing Private Methods", "description": "Best practices for private methods." },
  { "id": 48, "title": "Refactoring Specs", "description": "Improve readability and structure." },
  { "id": 49, "title": "Avoiding Over-Mocking", "description": "Learn when not to mock." },
  { "id": 50, "title": "Spec Smells", "description": "Identify brittle and unclear tests." },

  { "id": 51, "title": "Custom Matchers (Advanced)", "description": "Build parameterized matchers." },
  { "id": 52, "title": "Metadata", "description": "Tag specs with metadata." },
  { "id": 53, "title": "Conditional Hooks", "description": "Run hooks based on metadata." },
  { "id": 54, "title": "RSpec Configuration", "description": "Customize RSpec behavior globally." },
  { "id": 55, "title": "Formatter Options", "description": "Change output formats." },
  { "id": 56, "title": "Profiling Slow Specs", "description": "Identify slow examples." },
  { "id": 57, "title": "Order Randomization", "description": "Detect order dependencies." },
  { "id": 58, "title": "RSpec Extensions", "description": "Extend RSpec with plugins." },
  { "id": 59, "title": "Testing Legacy Code", "description": "Write specs for untested code." },
  { "id": 60, "title": "RSpec Philosophy", "description": "Learn best practices and testing mindset." }
]

export default lessons;
