const lessons = [
  { "id": 1, "title": "What is RSpec?", "description": "Understand the purpose of RSpec and how it differs from other testing frameworks.", "available": true },
  { "id": 2, "title": "Installing RSpec", "description": "Set up RSpec in a Ruby project using Bundler.", "available": true },
  { "id": 3, "title": "Running Your First Spec", "description": "Execute your first RSpec test and understand the output.", "available": true },
  { "id": 4, "title": "describe Blocks", "description": "Group related tests using describe blocks.", "available": true },
  { "id": 5, "title": "it Blocks", "description": "Define individual examples with it blocks.", "available": true },
  { "id": 6, "title": "Basic Expectations", "description": "Write expectations using expect().to.", "available": true },
  { "id": 7, "title": "Equality Matchers", "description": "Use eq, eql, and equal matchers correctly.", "available": true },
  { "id": 8, "title": "Truthiness Matchers", "description": "Test true, false, and nil values.", "available": true },
  { "id": 9, "title": "Comparison Matchers", "description": "Use be >, be <, and other comparison matchers.", "available": true },
  { "id": 10, "title": "Collection Matchers", "description": "Test arrays and hashes using include and match_array.", "available": true },
  { "id": 11, "title": "String Matchers", "description": "Test strings with start_with, end_with, and match.", "available": true },
  { "id": 12, "title": "Type Matchers", "description": "Use be_a and kind_of matchers.", "available": true },
  { "id": 13, "title": "Predicate Matchers", "description": "Use be_empty, be_valid and custom predicates.", "available": true },
  { "id": 14, "title": "Using subject", "description": "Define and use subject in your specs.", "available": true },
  { "id": 15, "title": "Using let", "description": "Create memoized helper variables with let.", "available": true },
  { "id": 16, "title": "let vs let!", "description": "Understand lazy vs eager evaluation.", "available": false },
  { "id": 17, "title": "Nested describe Blocks", "description": "Organize specs with nested contexts.", "available": false },
  { "id": 18, "title": "context Blocks", "description": "Use context to describe different states.", "available": false },
  { "id": 19, "title": "before Hooks", "description": "Run setup code with before.", "available": false },
  { "id": 20, "title": "after Hooks", "description": "Run teardown code with after.", "available": false },
  { "id": 21, "title": "around Hooks", "description": "Wrap examples with around hooks.", "available": false },
  { "id": 22, "title": "Multiple Expectations", "description": "Write more than one expectation per example.", "available": false },
  { "id": 23, "title": "aggregate_failures", "description": "Group failures in a single example.", "available": false },
  { "id": 24, "title": "Pending Examples", "description": "Mark tests as pending or skipped.", "available": false },
  { "id": 25, "title": "Focused Specs", "description": "Run specific examples using fit and fdescribe.", "available": false },
  { "id": 26, "title": "Shared Contexts", "description": "Reuse setup code across specs.", "available": false },
  { "id": 27, "title": "Shared Examples", "description": "Reuse behavior definitions.", "available": false },
  { "id": 28, "title": "Custom Matchers (Basic)", "description": "Create your first custom matcher.", "available": false },
  { "id": 29, "title": "Failure Messages", "description": "Customize matcher failure output.", "available": false },
  { "id": 30, "title": "Composing Matchers", "description": "Combine matchers using and/or.", "available": false },
  { "id": 31, "title": "Spies Basics", "description": "Observe method calls without stubbing.", "available": false },
  { "id": 32, "title": "allow and receive", "description": "Stub methods using allow().to receive.", "available": false },
  { "id": 33, "title": "expect to receive", "description": "Set expectations on method calls.", "available": false },
  { "id": 34, "title": "Return Values in Mocks", "description": "Configure mocked return values.", "available": false },
  { "id": 35, "title": "Raising Errors", "description": "Test exceptions using raise_error.", "available": false },
  { "id": 36, "title": "Yielding Blocks", "description": "Test methods that yield blocks.", "available": false },
  { "id": 37, "title": "Instance Doubles", "description": "Use instance_double safely.", "available": false },
  { "id": 38, "title": "Class Doubles", "description": "Use class_double for constants.", "available": false },
  { "id": 39, "title": "Verifying Doubles", "description": "Ensure mocks match real objects.", "available": false },
  { "id": 40, "title": "Partial Doubles", "description": "Stub real objects carefully.", "available": false },
  { "id": 41, "title": "Stubbing Constants", "description": "Override constants during tests.", "available": false },
  { "id": 42, "title": "Message Chains", "description": "Stub chained method calls.", "available": false },
  { "id": 43, "title": "have_received Matcher", "description": "Verify spies after execution.", "available": false },
  { "id": 44, "title": "Order of Calls", "description": "Test method call order.", "available": false },
  { "id": 45, "title": "Argument Matching", "description": "Match method arguments.", "available": false },
  { "id": 46, "title": "Time Helpers", "description": "Freeze and travel time in tests.", "available": false },
  { "id": 47, "title": "Testing Private Methods", "description": "Best practices for private methods.", "available": false },
  { "id": 48, "title": "Refactoring Specs", "description": "Improve readability and structure.", "available": false },
  { "id": 49, "title": "Avoiding Over-Mocking", "description": "Learn when not to mock.", "available": false },
  { "id": 50, "title": "Spec Smells", "description": "Identify brittle and unclear tests.", "available": false },
  { "id": 51, "title": "Custom Matchers (Advanced)", "description": "Build parameterized matchers.", "available": false },
  { "id": 52, "title": "Metadata", "description": "Tag specs with metadata.", "available": false },
  { "id": 53, "title": "Conditional Hooks", "description": "Run hooks based on metadata.", "available": false },
  { "id": 54, "title": "RSpec Configuration", "description": "Customize RSpec behavior globally.", "available": false },
  { "id": 55, "title": "Formatter Options", "description": "Change output formats.", "available": false },
  { "id": 56, "title": "Profiling Slow Specs", "description": "Identify slow examples.", "available": false },
  { "id": 57, "title": "Order Randomization", "description": "Detect order dependencies.", "available": false },
  { "id": 58, "title": "RSpec Extensions", "description": "Extend RSpec with plugins.", "available": false },
  { "id": 59, "title": "Testing Legacy Code", "description": "Write specs for untested code.", "available": false },
  { "id": 60, "title": "RSpec Philosophy", "description": "Learn best practices and testing mindset.", "available": false }
];

export default lessons;
